name: Build LetDX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26
          go-version-file: LetDD/go.mod
          cache-dependency-path: LetDD/go.sum

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@d003170672d8166e07ad7d62459ad713c84a1d27
        with:
          llvm-version: 22

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.2.0
        with:
          cmake-version: 4.x

      - name: Configure CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build --config Release
